/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package csmclient;

import HienThi.FormClient_Play;
import action.SetTime;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import question.BoCauHoi;
import structure.Global;
import structure.define;
/**
 *
 * @author Mr.Tran
 */
public class CsmclientMainGui extends javax.swing.JFrame {

    /**
     * Creates new form CsmclientMainGui
     */
    Calendar startCal;
    public CsmclientMainGui() {
        initComponents();
        
        
        Rectangle maxBounds = GraphicsEnvironment.getLocalGraphicsEnvironment().
        getMaximumWindowBounds();
        this.setSize(maxBounds.width, maxBounds.height);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        startCal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String starttime = sdf.format(startCal.getTime());
        long timelilis = startCal.getTimeInMillis();
        
        txt_start_time.setText(starttime);
        //clock.setText(String.format("%02d:%02d", 5,0));
//        settime = new SetTime(timelilis);
//        settime.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_start_time = new javax.swing.JTextField();
        txt_use_time = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        btnLamBai = new javax.swing.JButton();
        bt_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSM CLIENT");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onclosewindows(evt);
            }
        });

        txt_start_time.setEditable(false);
        txt_start_time.setPreferredSize(new java.awt.Dimension(70, 20));

        txt_use_time.setEditable(false);
        txt_use_time.setPreferredSize(new java.awt.Dimension(70, 20));

        txtKetQua.setEditable(false);
        txtKetQua.setPreferredSize(new java.awt.Dimension(70, 20));

        jLabel1.setText("Thời gian đăng nhập");

        jLabel2.setText("Thời gian làm bài");

        jLabel4.setText("Kết quả");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clock"));

        clock.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        clock.setForeground(new java.awt.Color(0, 51, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnLamBai.setText("Làm bài thi");
        btnLamBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamBaiActionPerformed(evt);
            }
        });

        bt_logout.setText("Đăng xuất");
        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnChiTiet.setText("Xem chi tiết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_start_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKetQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_use_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(bt_logout))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnLamBai)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnChiTiet))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_logout, btnChiTiet, btnLamBai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_start_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_use_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamBai)
                    .addComponent(btnChiTiet))
                .addGap(30, 30, 30)
                .addComponent(bt_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_logout, btnChiTiet, btnLamBai});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
    try {
            
            
            Global.objectOutputStream.writeObject("LOGOUT");
         
            String response = (String) Global.objectInputStream.readObject();
            if(response.startsWith(define.SUCCESS))
            {
                //settime.stop();
                this.dispose();
                CsmclientLoginGui logingui = new CsmclientLoginGui();
                logingui.setVisible(true);
                Global.loginGui = logingui;
                
                System.out.println("LOGOUT finish");
            }
            Global.objectInputStream.close();
            Global.objectOutputStream.close();
            Global.loginSocket.close();
            
            
        } catch (IOException ex) {
            Logger.getLogger(CsmclientMainGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CsmclientMainGui.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void onclosewindows(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onclosewindows
        // TODO add your handling code here:
       // settime.stop();
    }//GEN-LAST:event_onclosewindows

    private void btnLamBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamBaiActionPerformed
        // TODO add your handling code here:
        
        // gui ma yeu cau lam bai thi len server         
        try {
            Global.objectOutputStream.writeObject("QUESTION");
            
            Global.boCauHoi = (BoCauHoi) Global.objectInputStream.readObject();
            
            if(Global.boCauHoi.getDs().size() > 0){
                // Ghi nhan thoi gian lam bai - va tinh nguoc thoi gian.
                startCal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                String starttime = sdf.format(startCal.getTime());
                long timelilis = startCal.getTimeInMillis();
                
                // hien thi ra text thoi gian bat dau lam bai
                Global.mainGui.txt_use_time.setText(starttime);
                
                // set time đếm ngược
               
                
               // Global.threadtime = settime;
                
                // Neu co cau hoi tra ve tu server
                FormClient_Play formClient_Play = new FormClient_Play();
                Global.formClient_Play = formClient_Play;
                
                SetTime settime = new SetTime();
                settime.start();
                Global.checkTime = true;
                Global.threadtime = settime;
               // this.dispose();
                
                
            }
            else{
                // khong nhan dc cau hoi
                JOptionPane.showMessageDialog(null, "Vui lòng quay lại sau");
                
            }
        } catch (IOException ex) {
            Logger.getLogger(CsmclientMainGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CsmclientMainGui.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_btnLamBaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_logout;
    public javax.swing.JButton btnChiTiet;
    public javax.swing.JButton btnLamBai;
    public javax.swing.JLabel clock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txt_start_time;
    public javax.swing.JTextField txt_use_time;
    // End of variables declaration//GEN-END:variables
}
